import { computeTrainingLoad } from "../utils/trainingLoad";

type Activity = {
  sport_type: string;
  distance: number; // meters
  moving_time: number; // sec
  start_date_local: string;
  average_heartrate?: number | null;
  max_heartrate?: number | null;
};

type Predictions = {
  predictions?: Record<string, number>;
};

type WorkoutStep = {
  name: string;
  durationType: "Time" | "Distance";
  durationValue: number;
  intensity: "Warmup" | "Active" | "Resting" | "Cooldown";
};

type WorkoutExport = {
  fileName: string;
  workoutName: string;
  steps: WorkoutStep[];
};

const RUN_TYPES = new Set(["Run", "TrailRun", "VirtualRun"]);

function toDate(value: string) {
  const d = new Date(value);
  return Number.isNaN(d.getTime()) ? null : d;
}

function round1(v: number) {
  return Math.round(v * 10) / 10;
}

function paceFromSecPerKm(secPerKm: number) {
  const m = Math.floor(secPerKm / 60);
  const s = Math.round(secPerKm % 60);
  return `${m}:${String(s).padStart(2, "0")}/km`;
}

function stepTime(name: string, seconds: number, intensity: WorkoutStep["intensity"]): WorkoutStep {
  return { name, durationType: "Time", durationValue: seconds, intensity };
}

function stepDistance(name: string, meters: number, intensity: WorkoutStep["intensity"]): WorkoutStep {
  return { name, durationType: "Distance", durationValue: meters, intensity };
}

function escapeXml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function buildTcx(workout: WorkoutExport) {
  const stepsXml = workout.steps
    .map(
      (step, index) => `
      <Step>
        <StepId>${index + 1}</StepId>
        <Name>${escapeXml(step.name)}</Name>
        <DurationType>${step.durationType}</DurationType>
        <DurationValue>${step.durationValue}</DurationValue>
        <Intensity>${step.intensity}</Intensity>
        <TargetType>Open</TargetType>
      </Step>`
    )
    .join("");

  return `<?xml version="1.0" encoding="UTF-8"?>
<TrainingCenterDatabase xsi:schemaLocation="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd" xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Workouts>
    <Workout Sport="Running">
      <Name>${escapeXml(workout.workoutName)}</Name>${stepsXml}
      <Notes>Generated by FabRun</Notes>
    </Workout>
  </Workouts>
</TrainingCenterDatabase>`;
}

function downloadTextFile(fileName: string, content: string, mime = "application/xml") {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function analyze(rows: Activity[], predictions?: Predictions | null) {
  const now = new Date();
  const runs = rows
    .filter((r) => RUN_TYPES.has(r.sport_type))
    .map((r) => ({ ...r, date: toDate(r.start_date_local) }))
    .filter((r) => r.date != null)
    .sort((a, b) => (b.date!.getTime() - a.date!.getTime()));

  if (runs.length === 0) {
    return {
      type: "none",
      title: "Pas assez de données",
      plan: "Ajoute 2-3 sorties pour générer une séance ciblée.",
      why: ["Aucune sortie run exploitable."],
      confidence: "faible",
      workout: null as WorkoutExport | null,
    };
  }

  const inLastDays = (days: number) =>
    runs.filter((r) => now.getTime() - r.date!.getTime() <= days * 24 * 3600 * 1000);

  const runs28 = inLastDays(28);
  const metrics = computeTrainingLoad(rows);
  const km7 = metrics.acute7Km;
  const chronicPerWeek = metrics.chronic28AvgKm;
  const km28 = chronicPerWeek * 4;
  const acr = metrics.acr ?? 0;

  const hrSamples = runs28
    .map((r) => ({
      avg: typeof r.average_heartrate === "number" ? r.average_heartrate : null,
      max: typeof r.max_heartrate === "number" ? r.max_heartrate : null,
    }))
    .filter((h) => h.avg != null || h.max != null);
  const hrCoverage = runs28.length > 0 ? hrSamples.length / runs28.length : 0;
  const observedHrMax = Math.max(
    ...hrSamples.map((h) => Math.max(h.max ?? 0, (h.avg ?? 0) + 10)),
    0
  );

  const recent48h = inLastDays(2);
  const hadHard48h = recent48h.some((r) => {
    const avgHr = r.average_heartrate ?? 0;
    const km = r.distance / 1000;
    const longSteadyHard = km >= 10 && r.moving_time >= 45 * 60 && observedHrMax > 0 && avgHr >= observedHrMax * 0.82;
    const intenseByHr = observedHrMax > 0 && avgHr >= observedHrMax * 0.88;
    return intenseByHr || longSteadyHard;
  });

  const remainingToday = metrics.remainingNow;

  const fiveKSec = predictions?.predictions?.["5k"];
  const pace5k = typeof fiveKSec === "number" && fiveKSec > 0 ? fiveKSec / 5 : null;
  const rep400 = pace5k ? Math.round(pace5k * 0.4) : null;
  const rep1000 = pace5k ? Math.round(pace5k + 12) : null; // ~5K pace + 12s/km

  const reasons: string[] = [];
  reasons.push(`Charge 7j ${round1(km7)} km, 28j ${round1(km28)} km (ACR ${round1(acr)}).`);
  if (hrCoverage > 0) reasons.push(`Données FC sur ${Math.round(hrCoverage * 100)}% des sorties récentes.`);
  if (hadHard48h) reasons.push("Séance intense détectée dans les 48 dernières heures.");

  if (hadHard48h) {
    const easyKm = Math.max(0, Math.min(remainingToday, 6.0));
    return {
      type: "recovery",
      title: "Séance récupération",
      plan:
        remainingToday <= 1.5
          ? `0-${round1(remainingToday)} km très facile (ou vélo doux / repos).`
          : `${round1(Math.min(remainingToday, 6))}-${round1(Math.min(remainingToday, 7))} km très facile, allure confortable.`,
      why: reasons,
      confidence: hrCoverage >= 0.5 ? "moyenne" : "faible",
      workout:
        easyKm < 0.5
          ? null
          : {
              fileName: "fabrun-recup.tcx",
              workoutName: "FabRun Recuperation",
              steps: [
                stepTime("Echauffement", 600, "Warmup"),
                stepDistance(`Endurance facile ${easyKm.toFixed(1)} km`, Math.round(easyKm * 1000), "Active"),
                stepTime("Retour au calme", 300, "Cooldown"),
              ],
            },
    };
  }

  if (remainingToday < 3) {
    return {
      type: "recovery",
      title: "Séance courte uniquement",
      plan: `Budget du jour limité: max ${round1(remainingToday)} km facile. Pas de fractionné aujourd'hui.`,
      why: [...reasons, `Budget restant calculé aujourd'hui: ${round1(remainingToday)} km.`],
      confidence: hrCoverage >= 0.5 ? "moyenne" : "faible",
      workout:
        remainingToday < 0.5
          ? null
          : {
              fileName: "fabrun-court-facile.tcx",
              workoutName: "FabRun Court Facile",
              steps: [
                stepTime("Echauffement", 600, "Warmup"),
                stepDistance(`Footing facile ${round1(remainingToday)} km`, Math.round(remainingToday * 1000), "Active"),
                stepTime("Retour au calme", 300, "Cooldown"),
              ],
            },
    };
  }

  if (acr >= 0.85 && acr <= 1.2) {
    const qualityWorkout: WorkoutExport | null =
      rep400 == null
        ? null
        : {
            fileName: "fabrun-6x400.tcx",
            workoutName: "FabRun 6x400",
            steps: [
              stepTime("Echauffement", 900, "Warmup"),
              stepDistance(`400m rapide (~${rep400}s) #1`, 400, "Active"),
              stepDistance("Recup 200m trot #1", 200, "Resting"),
              stepDistance(`400m rapide (~${rep400}s) #2`, 400, "Active"),
              stepDistance("Recup 200m trot #2", 200, "Resting"),
              stepDistance(`400m rapide (~${rep400}s) #3`, 400, "Active"),
              stepDistance("Recup 200m trot #3", 200, "Resting"),
              stepDistance(`400m rapide (~${rep400}s) #4`, 400, "Active"),
              stepDistance("Recup 200m trot #4", 200, "Resting"),
              stepDistance(`400m rapide (~${rep400}s) #5`, 400, "Active"),
              stepDistance("Recup 200m trot #5", 200, "Resting"),
              stepDistance(`400m rapide (~${rep400}s) #6`, 400, "Active"),
              stepDistance("Recup 200m trot #6", 200, "Resting"),
              stepTime("Retour au calme", 600, "Cooldown"),
            ],
          };

    return {
      type: "quality",
      title: "Séance qualité (fractionné)",
      plan:
        rep400 && rep1000
          ? `Option A: 6 x 400 m en ${rep400}s (récup 200 m trot). Option B: 4 x 1 km en ${paceFromSecPerKm(
              rep1000
            )} (récup 2').`
          : "Option A: 6 x 400 m allure 5K (récup 200 m trot). Option B: 4 x 1 km allure 10K (récup 2').",
      why: [...reasons, `Budget restant estimé: ${round1(remainingToday)} km (ok pour une séance qualité).`],
      confidence: hrCoverage >= 0.5 ? "haute" : "moyenne",
      workout: qualityWorkout,
    };
  }

  const easyKm = Math.max(0, Math.min(remainingToday, 8.0));
  return {
    type: "build",
    title: "Séance endurance active",
    plan: `${round1(Math.min(remainingToday, 8))}-${round1(Math.min(remainingToday, 10))} km en endurance, contrôlé.`,
    why: reasons,
    confidence: hrCoverage >= 0.5 ? "moyenne" : "faible",
    workout:
      easyKm < 0.5
        ? null
        : {
            fileName: "fabrun-endurance.tcx",
            workoutName: "FabRun Endurance Active",
            steps: [
              stepTime("Echauffement", 600, "Warmup"),
              stepDistance(`Endurance ${easyKm.toFixed(1)} km`, Math.round(easyKm * 1000), "Active"),
              stepTime("Retour au calme", 300, "Cooldown"),
            ],
          },
  };
}

export default function NextSessionCard({
  rows,
  predictions,
}: {
  rows: Activity[];
  predictions?: Predictions | null;
}) {
  const rec = analyze(rows, predictions);
  const confClass =
    rec.confidence === "haute" ? "next-conf-high" : rec.confidence === "moyenne" ? "next-conf-medium" : "next-conf-low";

  return (
    <section className="next-session-card">
      <div className="next-session-head">
        <div className="next-session-title">Prochaine séance conseillée</div>
        <span className={`next-session-conf ${confClass}`}>Fiabilité {rec.confidence}</span>
      </div>
      <div className="next-session-type">{rec.title}</div>
      <div className="next-session-plan">{rec.plan}</div>
      {rec.workout && (
        <div className="next-session-export">
          <button
            className="next-session-export-btn"
            type="button"
            onClick={() => {
              const tcx = buildTcx(rec.workout!);
              downloadTextFile(rec.workout!.fileName, tcx);
            }}
          >
            Télécharger séance Garmin (.tcx)
          </button>
          <div className="next-session-export-hint">
            Import ensuite le fichier dans Garmin Connect.
          </div>
        </div>
      )}
      <ul className="next-session-why">
        {rec.why.map((r, i) => (
          <li key={`${r}-${i}`}>{r}</li>
        ))}
      </ul>
    </section>
  );
}
